version: '2'

services:
  fetch:
    image: nouchka/hackmyresume
    command: curl -o /usr/share/nginx/html/resume.json https://raw.githubusercontent.com/nouchka/japromis.katagena.com/master/resume.json
    volumes:
      - /tmp/resume:/usr/share/nginx/html
  hackmyresume:
    build: .
    image: nouchka/hackmyresume
    environment:
      - OUTPUT_TEMPLATE=kendall
      - TEMPLATE_GIT=https://github.com/nouchka/jsonresume-theme-kendall.git
      - PHONE=+33602030405
      - EMAIL=docker@katagena.com
      - ADDRESS=25 Rue Delphin Loche
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/resume:/usr/share/nginx/html
